version: "3"

services:
  cypherapp-mempool:
    image: cypherapp-mempool:v0.1.0 
    volumes:
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/data/cert.pem"
      - "$GATEKEEPER_DATAPATH/keys.properties:/data/keys.properties"
      - "$APP_SCRIPT_PATH/config.toml:/data/config.toml"
      - "$GATEKEEPER_DATAPATH/htpasswd:/htpasswd/htpasswd"
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      - "traefik.frontend.rule=Host:mempool.localhost"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.auth.basic.usersFile=/htpasswd/htpasswd"
    ports:
        - "3000:3000"
networks:
  cyphernodeappsnet:
    external: true
